### ISSUE TITLE
Why is every single function in its own file?

### ISSUE THREAD

**Issue by johnwbyrd** [cmcqueen/aes-min#2]

**Comment by cmcqueen** [comment]
In the past, I've worked with some fairly dumb compilers for very small microprocessors, where the linker wasn't optimised enough to remove unused functions. Putting functions in separate files allows for selecting which functions are linked in.

But probably those poorly-optimising compilers are rare these days, so I should probably change it to suit the most common situation, which is a compiler with a decent linker.

**Comment by cmcqueen** [comment]
I've also provided an alternative implementation of the S-box and inverse S-box. In `Makefile.am` you can see how different source files are linked in to select the "small" implementation of the S-box.  I could instead use a preprocessor `#ifdef`.

**Comment by cmcqueen** [comment]
In version 0.3.0, I've moved the code for the AES block encrypt/decrypt operations into a single pair of `aes-min.c` and `aes-min.h` files.

The AES-GCM GHASH function (Galois 128-bit multiply) is still in separate source files.
