### ISSUE TITLE
Support Request, How to use the library

### ISSUE THREAD

**Issue by bobsort** [cmcqueen/aes-min#4]
1. How to use this library?
2. What is schedule, block, start_key and key work and their relation to key, IV and data?
3. What is gcm (`gcm.h`, `gcm.c`), do I need to include them too?
4. I'm trying to fit this library plus some other code in a ATTiny85 (6KB), do I need all the files in library or just  `aes-min.c` and `aes-min.h`?
5. Is it possible to directly work on data block (array) instead of copying it to another array?
6. And finally, I don't think I can fit your copyright inside ATTiny with the code, where do you like me to put it?

**Comment by cmcqueen** [comment]
1. What sort of encryption do you want to do? For basic AES encryption, you could look at [`tests/aes-encrypt-test.c`](/cmcqueen/aes-min/blob/master/tests/aes-encrypt-test.c) as an example of how to use the encryption functions.
2. See the comments on functions `aes128_encrypt()`, `aes128_otfks_decrypt_start_key()` and `aes128_otfks_decrypt()`. Do they answer these questions?
3. The gcm files are needed for doing the Galois field multiplication used in [AES-GCM mode](https://en.wikipedia.org/wiki/Galois/Counter_Mode). If you're not doing AES-GCM mode, then the gcm files are not needed.
4. You only need `aes-min.c` and `aes-min.h` for most usage. If you're doing AES-GCM mode, then you additionally need `gcm.c` and `gcm.h`.
5. I'm not sure quite what you mean.
6. I don't expect the compiled binary to include a copy of the copyright and license text; only source code. Sorry, I'm using the MIT license as-is, but that part of the text is ambiguous. I should be able to clarify that in the license file if that would help.
