### ISSUE TITLE
gcm_test uses gcm_mul even if TEST_GCM_MUL_TABLE4 is selected

### ISSUE THREAD

**Issue by pilatomic** [cmcqueen/aes-min#6]
Hello,

I've noticed that at line 390 of gcm_test.c, gcm_mul is called regardless of the value of gcm_mul_implementation_t.
I seems to me that this area could use the same switch / case statement used to select the gcm_mul implementation at the other places in this function.

Is this a simple oversight, or on purpose ?

**Comment by cmcqueen** [comment]
Thanks for reporting this. I think it was an oversight. I've committed a fix for it.
